defaults: &defaults
    # Required.
    client_id: <%= options[:client_id] %>
    client_secret: <%= options[:client_key] %>
    authorization_server: <%= options[:auth_server] %>
    requested_scope:  <%= options[:requested_scope] %>
  


development:
  <<: *defaults

test: &test
  <<: *defaults

production: &production
  <<: *defaults

# staging:
#   <<: *production
#
# cucumber:
#   <<: *test